### ISSUE TITLE
ROADMAP - meta issue

### ISSUE THREAD

**Issue by arwer13** [lidofinance/state-mate#15]
## Backlog
- [ ] fix confusion with `mustRevert` and/or `result` check fields
- [ ] make state-mate a package usable in other code bases as a module
- [ ] iteration on README: describe new features
- [ ] don't allow `bytes` arg types be specified `0x` which is parsed as hex number but string
- [ ] schema-based state config verification
- [ ] generation mode: support auto detection of proxy type (OssifiableProxy-like + Transparent proxy)
- [ ] #14 
- [ ] support thorough ACL check for non-enumerable ACL via event-based
- [ ] add option to check that saved ABIs and explorer ABIs are equal
- [ ] remove duplication of saved ABIs for proxies

**Comment by arwer13** [comment]
Let's fix not clear message:
```
✘ .hasRole(0x4b43b36766bde12c5e9cbbc37d15f8d1f769f08f54720ab370faeb4ce893753a, 0x73b047fe6337183A454c5217241D780a932777bD): REVERTED with: expected false to be true
```
